//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\oscar\Desktop\Nueva carpeta\Recetario.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RecetarioParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IRecetarioVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.recetario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecetario([NotNull] RecetarioParser.RecetarioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.receta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceta([NotNull] RecetarioParser.RecetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNombre([NotNull] RecetarioParser.NombreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.porciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPorciones([NotNull] RecetarioParser.PorcionesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.preparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreparacion([NotNull] RecetarioParser.PreparacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.coccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCoccion([NotNull] RecetarioParser.CoccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.calorias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalorias([NotNull] RecetarioParser.CaloriasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.ingredientes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIngredientes([NotNull] RecetarioParser.IngredientesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.elaboracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboracion([NotNull] RecetarioParser.ElaboracionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.ing_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIng_item([NotNull] RecetarioParser.Ing_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RecetarioParser.ela_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEla_item([NotNull] RecetarioParser.Ela_itemContext context);
}
